#!/bin/bash

export HOME=/var/lib/fio
chown -R fio:fio /var/lib/fio

EXTRA=
PUB=$(curl -s https://address.works)
[ -z "$PUB" ] && EXTRA="--p2p-server-address=${PUB}:3856"

if [ ! -f /var/lib/fio/data/blocks/blocks.log ]; then
	echo "fetching blocks.log, this can take a long time"
	runuser -u fio -- aria2c -j 3 -x 3 --summary-interval=30 --enable-color=false https://snap.blockpane.com/testnet-latest-blocks.txz
  echo "extracting blocks"
	runuser -u fio -- tar -xvS -I'pixz' -f testnet-latest-blocks.txz
  rm -f testnet-latest-blocks.txz
	popd >/dev/null
fi

if [ ! -f /var/lib/fio/data/state/shared_memory.bin ]; then
  echo "restoring state from snapshot"
	exec restrict -uid=$(id -u fio) -gid=$(id -g fio) /usr/local/bin/fio-nodeos --data-dir /var/lib/fio/data --config-dir /etc/fio/nodeos --snapshot $(ls -1 /var/lib/fio/data/snapshots/*bin|head -1) $EXTRA
else
	exec restrict -uid=$(id -u fio) -gid=$(id -g fio) /usr/local/bin/fio-nodeos --data-dir /var/lib/fio/data --config-dir /etc/fio/nodeos --genesis-json /etc/fio/nodeos/genesis.json $EXTRA
fi
