#!/bin/bash

export HOME=/var/lib/fio
chown -R fio:fio /var/lib/fio

EXTRA=
PUB=$(curl -s https://address.works)
[ -z "$PUB" ] && EXTRA="--p2p-server-address=$PUB:3856"

if [ ! -f /var/lib/fio/data/blocks/blocks.log ]; then
  echo "fetching history archive, this can take a long time"
	runuser -u fio -- aria2c -j 3 -x 3 --summary-interval=30 --enable-color=false https://snap.blockpane.com/testnet-latest-history.txz
  echo "extracting history archive"
	runuser -u fio -- tar -xvS -I'pixz' -f testnet-latest-history.txz || exit
  rm -f testnet-latest-history.txz
fi

exec restrict -uid=$(id -u fio) -gid=$(id -g fio) /usr/local/bin/fio-nodeos --data-dir /var/lib/fio/data --config-dir /etc/fio/nodeos --genesis-json /etc/fio/nodeos/genesis.json $EXTRA
